name: AGK Health Check

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  health:
    name: Antigravity Kit Health Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Run AGK Health Check
        run: npx @kamishino/antigravity-kit doctor
