/**
 * agk agents — Scan, register, find, and manage AI agents
 *
 * Subcommands:
 *   agk agents           → Scan and register agents in GEMINI.md + generate AGENTS.md
 *   agk agents find <q>  → Search community agent templates
 *   agk agents list      → List installed agents
 */

const fs = require("fs-extra");
const path = require("path");
const chalk = require("chalk");
const { execSync } = require("child_process");
const { parseFrontmatter } = require("../lib/frontmatter");

const REGISTRY_START = "<!-- AGK_AGENT_REGISTRY_START -->";
const REGISTRY_END = "<!-- AGK_AGENT_REGISTRY_END -->";

async function run(projectDir, args = []) {
  const subcommand = args[0] || "register";

  switch (subcommand) {
    case "register":
      return await register(projectDir);
    case "find":
      return await findAgents(projectDir, args.slice(1));
    case "list":
      return await listAgents(projectDir);
    default:
      // Treat unknown subcommand as default "register"
      return await register(projectDir);
  }
}

async function register(projectDir) {
  const agentsDir = path.join(projectDir, ".agent", "agents");

  if (!(await fs.pathExists(agentsDir))) {
    console.error(
      chalk.red(
        "\n❌ No .agent/agents/ directory found. Run `agk init` first.\n",
      ),
    );
    return 1;
  }

  // 1. Scan all agent .md files
  const files = (await fs.readdir(agentsDir)).filter((f) => f.endsWith(".md"));

  if (files.length === 0) {
    console.log(chalk.yellow("\n⚠️  No agents found in .agent/agents/\n"));
    return 0;
  }

  console.log(chalk.cyan("\n🤖 AGK Agent Registry\n"));

  const agents = [];
  for (const file of files) {
    const content = await fs.readFile(path.join(agentsDir, file), "utf8");
    const meta = parseFrontmatter(content);
    if (meta && meta.name) {
      const triggers = meta.triggers || [];
      const description = meta.description || "";
      agents.push({
        name: meta.name,
        description,
        triggers,
        file: `.agent/agents/${file}`,
      });
      const triggerStr = triggers.length > 0 ? triggers.join(", ") : "(none)";
      console.log(
        `  ${chalk.green("✓")} ${chalk.bold(meta.name)} — ${chalk.gray(triggerStr)}`,
      );
    }
  }

  // 2. Build the registry table for GEMINI.md
  const tableRows = agents
    .map((a) => {
      const triggers =
        a.triggers.length > 0 ? `\`${a.triggers.join("`, `")}\`` : "—";
      return `| ${a.name} | ${triggers} | \`${a.file}\` |`;
    })
    .join("\n");

  const registryBlock = [
    REGISTRY_START,
    "| Agent | Triggers | File |",
    "|:---|:---|:---|",
    tableRows,
    REGISTRY_END,
  ].join("\n");

  // 3. Update GEMINI.md
  const geminiPath = path.join(projectDir, "GEMINI.md");
  if (await fs.pathExists(geminiPath)) {
    let geminiContent = await fs.readFile(geminiPath, "utf8");
    const startIdx = geminiContent.indexOf(REGISTRY_START);
    const endIdx = geminiContent.indexOf(REGISTRY_END);

    if (startIdx !== -1 && endIdx !== -1) {
      geminiContent =
        geminiContent.substring(0, startIdx) +
        registryBlock +
        geminiContent.substring(endIdx + REGISTRY_END.length);
      await fs.writeFile(geminiPath, geminiContent, "utf8");
    }
  }

  // 4. Generate AGENTS.md (open standard)
  await generateAgentsMd(projectDir, agents);

  console.log(
    chalk.green(`\n✅ Registered ${agents.length} agents in GEMINI.md`),
  );
  console.log(
    chalk.gray("   Auto-Dispatch is now active for AI assistants.\n"),
  );

  return 0;
}

/**
 * Generate AGENTS.md — the open standard for AI coding agents.
 * This file is read by Copilot, Codex, Jules, Cursor, and other AI tools.
 */
async function generateAgentsMd(projectDir, agents) {
  const lines = [
    "# AGENTS.md",
    "",
    "> This file follows the [AGENTS.md open standard](https://agents.md) for AI coding agents.",
    "> It is auto-generated by `agk agents`. Do not edit manually.",
    "",
    "## Project Agents",
    "",
    `This project uses **${agents.length} specialized AI agents** managed by [Antigravity Kit](https://github.com/kamishino/gemini-cli-workflow).`,
    "",
    "| Agent | Description | Triggers |",
    "|:---|:---|:---|",
  ];

  for (const agent of agents) {
    const triggers =
      agent.triggers.length > 0
        ? agent.triggers.slice(0, 5).join(", ") +
          (agent.triggers.length > 5 ? "..." : "")
        : "—";
    lines.push(`| **${agent.name}** | ${agent.description} | ${triggers} |`);
  }

  lines.push(
    "",
    "## Agent Configuration",
    "",
    "Agents are defined as Markdown files in `.agent/agents/` with YAML frontmatter:",
    "",
    "```yaml",
    "---",
    "name: Agent Name",
    "description: What this agent does",
    "triggers: [keyword1, keyword2]",
    "owns: [src/**]",
    "skills: [skill-name]",
    "---",
    "```",
    "",
    "## How to Add Agents",
    "",
    "```bash",
    "# Scaffold a new agent",
    'agk scaffold agent "My Agent" "Description"',
    "",
    "# Find community agents",
    "agk agents find react",
    "",
    "# Re-register all agents",
    "agk agents",
    "```",
    "",
    "## Skills",
    "",
    "Agents can declare required skills via the `skills` field.",
    "Install skills with `agk skills add <name>` from [skills.sh](https://skills.sh).",
    "",
  );

  const agentsMdPath = path.join(projectDir, "AGENTS.md");
  await fs.writeFile(agentsMdPath, lines.join("\n"), "utf8");
}

/**
 * Search for community agent templates via npx claude-code-templates
 * and npm search.
 */
async function findAgents(_projectDir, queryArgs) {
  const query = queryArgs.join(" ");

  if (!query) {
    console.log(chalk.yellow("\n⚠️  Missing search query."));
    console.log(chalk.gray('  Usage: agk agents find "react"\n'));
    return 1;
  }

  console.log(chalk.cyan(`\n🔍 Searching for agent templates: "${query}"\n`));

  let found = false;

  // Source 1: npm search for agent packages
  try {
    console.log(chalk.gray("  Searching npm for agent packages..."));
    const result = execSync(
      `npm search "claude agent ${query}" --json --long 2>nul`,
      {
        encoding: "utf8",
        timeout: 15000,
        stdio: "pipe",
      },
    );

    const packages = JSON.parse(result || "[]").slice(0, 5);
    if (packages.length > 0) {
      console.log(chalk.bold("\n  📦 npm packages:\n"));
      for (const pkg of packages) {
        console.log(
          `  ${chalk.green("•")} ${chalk.bold(pkg.name)} ${chalk.gray("v" + (pkg.version || "?"))}`,
        );
        if (pkg.description) {
          console.log(chalk.gray(`    ${pkg.description}`));
        }
        console.log(chalk.yellow(`    npm i ${pkg.name}\n`));
      }
      found = true;
    }
  } catch {
    // npm search failed — skip
  }

  // Source 2: GitHub search suggestion
  console.log(chalk.bold("  🐙 GitHub:\n"));
  console.log(
    chalk.gray(
      `  Search GitHub for agent templates: https://github.com/search?q=${encodeURIComponent(query + " agent AGENTS.md")}&type=repositories`,
    ),
  );
  console.log();

  // Source 3: Claude Code Templates
  console.log(chalk.bold("  📋 Claude Code Templates:\n"));
  console.log(chalk.gray(`  Browse agents at: https://aitmpl.com`));
  console.log(
    chalk.yellow(`  npx claude-code-templates@latest --agent "${query}"`),
  );
  console.log();

  // Source 4: skills.sh
  console.log(chalk.bold("  🔧 Skills.sh:\n"));
  console.log(chalk.yellow(`  agk skills find ${query}`));
  console.log();

  if (!found) {
    console.log(
      chalk.gray(
        "  Tip: You can also create your own agent with `agk scaffold agent`\n",
      ),
    );
  }

  return 0;
}

async function listAgents(projectDir) {
  const agentsDir = path.join(projectDir, ".agent", "agents");

  if (!(await fs.pathExists(agentsDir))) {
    console.log(chalk.yellow("\n📦 No agents installed."));
    console.log(chalk.gray("   Run: agk init\n"));
    return 0;
  }

  const files = (await fs.readdir(agentsDir)).filter((f) => f.endsWith(".md"));

  if (files.length === 0) {
    console.log(chalk.yellow("\n📦 No agents found.\n"));
    return 0;
  }

  console.log(chalk.cyan(`\n🤖 Installed Agents (${files.length})\n`));

  for (const file of files) {
    const content = await fs.readFile(path.join(agentsDir, file), "utf8");
    const meta = parseFrontmatter(content);
    const name = (meta && meta.name) || file.replace(".md", "");
    const desc = (meta && meta.description) || "";
    const skills = (meta && meta.skills) || [];
    const skillStr =
      skills.length > 0 ? chalk.blue(` [${skills.join(", ")}]`) : "";
    console.log(
      `  ${chalk.green("✓")} ${chalk.bold(name)}${desc ? chalk.gray(` — ${desc}`) : ""}${skillStr}`,
    );
  }

  console.log();
  return 0;
}

module.exports = { run };
